# Generated by Django 3.0.4 on 2020-04-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='环境',
        ),
    ]
