# Generated by Django 3.0.4 on 2020-04-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20200401_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='wx01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPMI', models.CharField(max_length=32)),
                ('USER', models.CharField(max_length=32)),
                ('PASS', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='环境',
        ),
    ]
